(define (make-account balance account-password)
  (let ((count-fail 0))
    (define (withdraw amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
                 balance)
          "Not enough balance"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (incorrect-password)
      (if (>= count-fail 7)
        (error "call-the-cops")
        (begin (set! count-fail (+ count-fail 1))
               (error "Incorrect password"))))
    (define (dispatch password m)
      (if (eq? account-password password)
        (cond ((eq? m 'withdraw) withdraw)
              ((eq? m 'deposit) deposit)
              (else (error "Unckown call -- MAKE-ACCOUNT"
                    m)))
        (incorrect-password)))
    dispatch))

(define acc (make-account 100 'secret-password))

((acc 'some-other-password 'deposit) 50)
